### ISSUE TITLE
Dark Mode compatibility. 

### ISSUE THREAD

**Issue by silvioaburto** [Lattice-Automation/seqviz#275]
**Summary of the feature idea**
Most modern websites use dark mode. I couldn't find a way to overwrite the colors of text from the component. At minimum it would be nice to be able to pass a variable of colorMode = "dark" | "light".  
 

When color mode is set to dark, text should be white. When color mode is set to light, text should be black.

**Description of the ideal solution**

**Comment by benweinberg89** [comment]
Here is some css for a dark mode experience. I did this using the dash wrapper [dash-seqviz](https://github.com/Full-Spectrum-Analytics/dash-seqviz), so may need to adapt for javascript:
```css
/* Dark mode styles for SeqViz */
#seqviz-wrapper.dark-mode {
    background-color: #1a1a2e;
    border-radius: 8px;
    padding: 0px;
}

#seqviz-wrapper.dark-mode text {
    fill: #e0e0e0 !important;
}

#seqviz-wrapper.dark-mode .la-vz-linear-scroller {
    background-color: #1a1a2e !important;
}

#seqviz-wrapper.dark-mode .la-vz-index-tick-label {
    fill: #6b7280 !important;
}

#seqviz-wrapper.dark-mode .la-vz-index-line,
#seqviz-wrapper.dark-mode .la-vz-index-tick {
    stroke: #374151 !important;
}

#seqviz-wrapper.dark-mode .la-vz-cut-site-text {
    fill: #f472b6 !important;
}

/* Search highlighting */
#seqviz-wrapper.dark-mode .la-vz-search {
    fill: rgba(237, 237, 113, 0.2) !important;
}

/* Selection highlighting - cyan/sky blue accent */
#seqviz-wrapper.dark-mode [data-testid="la-vz-selection-block"],
#seqviz-wrapper.dark-mode .la-vz-selection-block,
#seqviz-wrapper.dark-mode .la-vz-selection,
#seqviz-wrapper.dark-mode path.la-vz-selection {
    fill: rgba(56, 191, 248, 0.4) !important;
}

#seqviz-wrapper.dark-mode [data-testid="la-vz-selection-edge"],
#seqviz-wrapper.dark-mode .la-vz-selection-edge,
#seqviz-wrapper.dark-mode path.la-vz-selection-edge,
#seqviz-wrapper.dark-mode rect.la-vz-selection-edge {
    fill: #38bdf8 !important;
    stroke: #38bdf8 !important;
}
```
Send something like this to `bpColors` to change the basepair colors:
```json
"A": "#22d3ee",  # cyan
"T": "#f472b6",  # pink
"C": "#a3e635",  # lime
"G": "#fbbf24",  # amber
```

<img width="1442" height="494" alt="Image" src="https://github.com/user-attachments/assets/fc716383-7a56-49db-90a5-3e21c04f3882" />
